Develop
4GeeksAcademy/EveyZeram_todolist pull request #2
Opened 2023-11-19 23:30 UTC by EveyZeram

Hola, 

Ejercicio hecho, había alguna cosa que no me salía pero con la clase grabada me ha ayudado. Espero tus comentarios.
Te pediré tutorías para unas dudas.

2023-11-21 13:49 UTC, hchocobar requested changes
Review - Request changes.

@EveyZeram estás realizando un trabajo genial.

Solo quedó una funcionalidad incompleta:

## deleteTask

En esta función solo estás eliminando la tarea del array, pero no la eliminas en la API

Podrías reescribir esta función para que realice lo siguiente:

- [x] Eliminar la tarea en la API (método DELETE)
- [ ] Obtener las tareas desde la API (método GET) 

![imagen](https://github.com/4GeeksAcademy/EveyZeram_todolist/assets/45291267/4bb4d304-d6a5-462d-b36c-d2aebb24b42a)

2023-12-04 20:25 UTC, EveyZeram commented
Hola Héctor, 
He añadido el useEffect para cada vez que se cargue que traiga las tareas de la api, que las he creado en postman. Pero si borro el usuario se borran las tareas, no sé si es esto lo que querías exactamente. 
He añadido el DELETE dentro de deleteTask para borrar las tareas de la API, pero no sé cómo acceder al ID (he puesto label, id...) de la tarea para poder eliminarla, por lo que se intento eliminar me da error. 

![Captura Error](https://github.com/4GeeksAcademy/EveyZeram_todolist/assets/130219194/fddc9fa5-75b1-4298-99d4-e8f587881d69)

2023-12-04 23:31 UTC, hchocobar approved these changes
# Review 

- El error del delete lo tienes cuando armas la url del endpoint, estás agregando el lebel y deberías agregar el id.
Puedes verlo en el error (allí sale make the bed)

![imagen](https://github.com/4GeeksAcademy/EveyZeram_todolist/assets/45291267/d7fd7cb0-6184-4ec5-bbac-eb59dfa73bcf)

- El useEfect() te dará ese error cuando la agenda no esté creada.
Este es un caso en el cual podrías tratar el error (404 en este caso) y mostrarle al usuario que no hay una agenda creada y que cree una.

2023-12-07 15:16 UTC, EveyZeram commented
Lo del id lo había probado y me salía el mismo error, lo cambio pero sigue igual.
Hecho lo del get

2023-12-08 15:01 UTC, hchocobar approved these changes
# Review -

2023-12-10 21:20 UTC, merged